// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyItpxjcgjOFKdWkDlA_jIDhAa7Zlg_oE',
    appId: '1:139804228419:web:eafa826bdaca28e85f4df6',
    messagingSenderId: '139804228419',
    projectId: 'wisewallet-6010b',
    authDomain: 'wisewallet-6010b.firebaseapp.com',
    storageBucket: 'wisewallet-6010b.firebasestorage.app',
    measurementId: 'G-BLMV69C07W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNg7OSkAdGJzlcyWa7VSet2P6Row1wmwc',
    appId: '1:139804228419:android:f3d8ec6e13e906d85f4df6',
    messagingSenderId: '139804228419',
    projectId: 'wisewallet-6010b',
    storageBucket: 'wisewallet-6010b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg2tTu1MG8baZMddK_xxoe4wPQdTJ99FI',
    appId: '1:139804228419:ios:c60b06253e74b8f95f4df6',
    messagingSenderId: '139804228419',
    projectId: 'wisewallet-6010b',
    storageBucket: 'wisewallet-6010b.firebasestorage.app',
    iosBundleId: 'com.example.wiseWallett',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg2tTu1MG8baZMddK_xxoe4wPQdTJ99FI',
    appId: '1:139804228419:ios:c60b06253e74b8f95f4df6',
    messagingSenderId: '139804228419',
    projectId: 'wisewallet-6010b',
    storageBucket: 'wisewallet-6010b.firebasestorage.app',
    iosBundleId: 'com.example.wiseWallett',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyItpxjcgjOFKdWkDlA_jIDhAa7Zlg_oE',
    appId: '1:139804228419:web:a20cb32a49790ae85f4df6',
    messagingSenderId: '139804228419',
    projectId: 'wisewallet-6010b',
    authDomain: 'wisewallet-6010b.firebaseapp.com',
    storageBucket: 'wisewallet-6010b.firebasestorage.app',
    measurementId: 'G-6NJ0HMY6SE',
  );
}
